postgreslq: &postgreslq
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

localhost: &localhost
  <<: *postgreslq
  port: %port%
  username: %username%
  host: localhost
  
deploy: &deploy
  <<: *postgreslq
  username: <%= ENV['SW_ACCOUNT_DB_USERNAME'] %>
  password: <%= ENV['SW_ACCOUNT_DB_PASSWORD'] %>

development:
  <<: *localhost
  database: %application_name%_development

testing:
  <<: *localhost
  database: %application_name%_testing

staging:
  <<: *deploy
  database: %application_name%_staging

production:
  <<: *deploy
  database: %application_name%_production
